version: '3.9'
services:
 client:
   stdin_open: true
   tty: true
   ports:
     - '3000:3000'
   build:
     dockerfile: Dockerfile.dev
     context: ./client
   volumes:
     - type: bind
       source: ./client
       target: /home/node
     - type: volume
       target: /home/node/node_modules
